name: automatically assign reviewers

on:
  schedule:
    - cron: "37 0 * * *" # At 00:37 UTC every day
  workflow_dispatch:

jobs:
  autoassign-reviewers:
    if: github.repository == 'leanprover-community/mathlib4'
    name: assign automatically proposed reviewers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: master
          sparse-checkout: |
            scripts/assign_reviewers.py

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.x'

      - name: assign reviewers
        env:
          ASSIGN_REVIEWERS_TOKEN: ${{ secrets.ASSIGN_REVIEWERS }}
        run: |
          python3 scripts/assign_reviewers.py
