name: Bench output summary

on:
  issue_comment:
    types: created

jobs:
  Produce_bench_summary:
    name: Post summary of benchmarking results
    if: github.event.issue.pull_request && (startsWith(github.event.comment.body, 'Here are the [benchmark results]'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: master
          sparse-checkout: |
            scripts/bench_summary.lean

      - name: Configure Lean
        uses: leanprover/lean-action@434f25c2f80ded67bba02502ad3a86f25db50709 # 2025-04-24
        with:
          auto-config: false
          use-github-cache: false
          use-mathlib-cache: false

      - name: Summarize bench output
        run: |
          {
            cat scripts/bench_summary.lean
            printf $'run_cmd BenchAction.addBenchSummaryComment %s "leanprover-community/mathlib4" %s' "${PR}" "${{ github.run_id }}"
          } |
            lake env lean --stdin
        env:
          PR:  ${{ github.event.issue.number }}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Remove "bench-after-CI"
        # we use curl rather than octokit/request-action so that the job won't fail
        # (and send an annoying email) if the labels don't exist
        run: |
          curl --request DELETE \
            --url https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels/bench-after-CI \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}'
